

1000000000 * 1.01/1/3                      #V= 1/3bh


import numpy
import numpy as np
#"Universe Byte Particle", "Matrix Array Containers" World Vision Virtual Bank...(1 Container= 100000 Bytes; 0 to 100; 
#'_PYRAMIDCHAIN.CONTAINERS_')

arr = np.arange(100).reshape(10,10)

print (arr)
